
on:
  workflow_call:
    inputs:
      newVersion:
        required: true
        type: string
jobs:
  ci-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag version
        run: |
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config --global user.name "${GH_USERNAME}"
          trimmed_version=$(echo ${{inputs.newVersion}} | rev | cut -d '.' -f 2- | rev)
          git switch "release/$trimmed_version"
          git tag -a ${{ inputs.newVersion }} -m ""
          git push origin ${{ inputs.newVersion }}