name: CI

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New version'
        required: false
        type: string


jobs:

  releases:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Releases automation
    environment: ci
    env:
          GH_USERNAME: ${{github.actor}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.



      - name: Install pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          cache: "pnpm"
          cache-dependency-path: ./pnpm-lock.yaml
      
      - name: New branch
        run: |

          trimmed_version=$(echo ${{github.event.inputs.newVersion}} | rev | cut -d '.' -f 2- | rev)
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config --global user.name "${GH_USERNAME}"
          git switch "release/#$trimmed_version" 2>/dev/null || git switch -c "release/#$trimmed_version";

          git push -u origin "release/#$trimmed_version"

      - name: Update version
        run: |
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config --global user.name "${GH_USERNAME}"
          trimmed_version=$(echo ${{github.event.inputs.newVersion}} | rev | cut -d '.' -f 2- | rev)
          git switch "release/#$trimmed_version"
          pnpm version ${{ github.event.inputs.newVersion }}
          git add . && git commit -m 'ci: bump version' && git push

      - name: Tag version
        run: |
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config --global user.name "${GH_USERNAME}"
          trimmed_version=$(echo ${{github.event.inputs.newVersion}} | rev | cut -d '.' -f 2- | rev)
          git switch "release/#$trimmed_version"
          git tag -a ${{ github.event.inputs.newVersion }} -m ""
          git push origin ${{ github.event.inputs.newVersion }}
        
      
